# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is A* Search Algorithm?
➔ A* is an informed search algorithm that efficiently finds the shortest path between a starting node and a target node in a graph by combining features of Dijkstra's algorithm and Greedy Best-First Search.

### 2. Explanation:
A* works by intelligently exploring a graph to find the optimal path. It does this by evaluating each potential step (node) using a function `f(n) = g(n) + h(n)`.
*   `g(n)` represents the actual cost from the starting node to the current node `n`. This is the "past cost" or "cost so far."
*   `h(n)` is a heuristic function that estimates the cost from the current node `n` to the goal node. This is the "future cost" or "estimated cost to go." For A* to guarantee finding the *shortest* path, `h(n)` must be "admissible" (never overestimates the true cost) and often "consistent" (monotonically non-decreasing along any path).
*   `f(n)` is the total estimated cost of the path through node `n` to the goal. A* always prioritizes exploring the node with the lowest `f(n)` value, making it a "best-first" search.

The algorithm maintains two lists to manage its search:
1.  **Open List (or Frontier):** A priority queue containing nodes that have been visited but not yet fully explored (i.e., their neighbors haven't all been processed). These are candidates for the next step, ordered by their `f(n)` value.
2.  **Closed List:** A set containing nodes that have already been fully explored. Once a node is in the closed list, A* won't revisit it unless a significantly better path to it is found (which typically doesn't happen with consistent heuristics).

A* starts at the initial node, adds it to the open list, and then repeatedly:
1.  Selects the node `n` from the open list with the lowest `f(n)`.
2.  If `n` is the goal, the path is found, and the algorithm terminates.
3.  Otherwise, `n` is moved from the open list to the closed list.
4.  It then generates all of `n`'s neighbors. For each neighbor:
    *   If the neighbor is in the closed list, ignore it.
    *   Calculate `g(neighbor)` (current `g(n)` + cost from `n` to `neighbor`).
    *   If the neighbor is not in the open list, or if the new `g(neighbor)` is lower than its previously recorded `g` value:
        *   Update its `g` value.
        *   Calculate its `f` value (`g(neighbor) + h(neighbor)`).
        *   Set `n` as its parent (for path reconstruction).
        *   Add it to the open list (or update its position if already there).

This process continues until the goal node is reached or the open list becomes empty (meaning no path exists).

### 3. Example:
Let's find the shortest path from 'S' (Start) to 'G' (Goal) on a simple 4x4 grid.
Movement cost: 1 for horizontal/vertical moves. Diagonal moves not allowed.
Heuristic `h(n)`: Manhattan distance to the goal (G).

Grid:
```text
S . . .
. X . .
. . . .
. . . G
```
Coordinates: S=(0,0), G=(3,3). 'X' is an obstacle at (1,1).

**Step 0: Initialize**
*   Open List: `[]`
*   Closed List: `[]`
*   `g(S)` = 0
*   `h(S)` = Manhattan distance from (0,0) to (3,3) = |3-0| + |3-0| = 3 + 3 = 6
*   `f(S)` = `g(S)` + `h(S)` = 0 + 6 = 6
*   Add `(f=6, S)` to Open List.
Open List: `[(f=6, S)]`

**Step 1: Expand S (0,0)**
*   Pop `S` (f=6) from Open List. Add `S` to Closed List.
*   Neighbors of `S` (0,0): (0,1) and (1,0).

    *   **Neighbor (0,1):**
        *   `g(0,1)` = `g(S)` + cost(S to (0,1)) = 0 + 1 = 1
        *   `h(0,1)` = |3-0| + |3-1| = 3 + 2 = 5
        *   `f(0,1)` = `g(0,1)` + `h(0,1)` = 1 + 5 = 6
        *   Parent: `S`. Add `(f=6, (0,1))` to Open List.
    *   **Neighbor (1,0):**
        *   `g(1,0)` = `g(S)` + cost(S to (1,0)) = 0 + 1 = 1
        *   `h(1,0)` = |3-1| + |3-0| = 2 + 3 = 5
        *   `f(1,0)` = `g(1,0)` + `h(1,0)` = 1 + 5 = 6
        *   Parent: `S`. Add `(f=6, (1,0))` to Open List.

*   Open List: `[(f=6, (0,1)), (f=6, (1,0))]` (Order might vary, assume (0,1) is picked next due to tie-breaking)
*   Closed List: `[S]`

**Step 2: Expand (0,1)**
*   Pop `(0,1)` (f=6) from Open List. Add `(0,1)` to Closed List.
*   Neighbors of `(0,1)`: `(0,0)` (in Closed), `(0,2)`, `(1,1)`.

    *   **Neighbor (0,2):**
        *   `g(0,2)` = `g(0,1)` + cost((0,1) to (0,2)) = 1 + 1 = 2
        *   `h(0,2)` = |3-0| + |3-2| = 3 + 1 = 4
        *   `f(0,2)` = `g(0,2)` + `h(0,2)` = 2 + 4 = 6
        *   Parent: `(0,1)`. Add `(f=6, (0,2))` to Open List.
    *   **Neighbor (1,1):** This is an obstacle 'X'. Ignore it.

*   Open List: `[(f=6, (1,0)), (f=6, (0,2))]` (Assume (1,0) is picked next)
*   Closed List: `[S, (0,1)]`

**Step 3: Expand (1,0)**
*   Pop `(1,0)` (f=6) from Open List. Add `(1,0)` to Closed List.
*   Neighbors of `(1,0)`: `(0,0)` (in Closed), `(2,0)`, `(1,1)`.

    *   **Neighbor (2,0):**
        *   `g(2,0)` = `g(1,0)` + cost((1,0) to (2,0)) = 1 + 1 = 2
        *   `h(2,0)` = |3-2| + |3-0| = 1 + 3 = 4
        *   `f(2,0)` = `g(2,0)` + `h(2,0)` = 2 + 4 = 6
        *   Parent: `(1,0)`. Add `(f=6, (2,0))` to Open List.
    *   **Neighbor (1,1):** This is an obstacle 'X'. Ignore it.

*   Open List: `[(f=6, (0,2)), (f=6, (2,0))]` (Assume (0,2) is picked next)
*   Closed List: `[S, (0,1), (1,0)]`

... The algorithm continues, always picking the node with the lowest `f` value. It will explore nodes like (0,2), (2,0), (0,3), (1,3), (2,3), (3,3).

**Later Step: Reaching the Goal**
Suppose the algorithm has processed nodes and `(2,3)` is currently the node with the lowest `f` value in the Open List.
*   `g(2,3)` = 5 (e.g., S -> (1,0) -> (2,0) -> (2,1) -> (2,2) -> (2,3) - path cost 5)
*   `h(2,3)` = |3-2| + |3-3| = 1 + 0 = 1
*   `f(2,3)` = 5 + 1 = 6

*   Pop `(2,3)` (f=6) from Open List. Add `(2,3)` to Closed List.
*   Neighbors of `(2,3)`: `(1,3)`, `(3,3)` (Goal!), `(2,2)` (already processed/in Open).

    *   **Neighbor (3,3) (Goal G):**
        *   `g(3,3)` = `g(2,3)` + cost((2,3) to (3,3)) = 5 + 1 = 6
        *   `h(3,3)` = |3-3| + |3-3| = 0 + 0 = 0
        *   `f(3,3)` = `g(3,3)` + `h(3,3)` = 6 + 0 = 6
        *   Parent: `(2,3)`. Add `(f=6, G)` to Open List.

*   Now, `G` (3,3) is in the Open List with `f=6`. Since it has the lowest `f`-value (or is tied), it will be chosen next.
*   Pop `G` (f=6) from Open List.
*   `G` is the goal node. Algorithm terminates.

Path Reconstruction (by backtracking parent pointers):
`G (3,3)` <- `(2,3)` <- `(2,2)` <- `(2,1)` <- `(2,0)` <- `(1,0)` <- `S (0,0)`
Final Path: S -> (1,0) -> (2,0) -> (2,1) -> (2,2) -> (2,3) -> G
Total Cost: 6

### 4. Algorithm Logic:
```python
import heapq # For priority queue implementation

def a_star_search(start_node, goal_node, graph, heuristic_function):
    '''
    Finds the shortest path between start_node and goal_node using A* algorithm.

    Args:
        start_node: The starting node.
        goal_node: The target node.
        graph: A graph object with methods:
               - get_neighbors(node): Returns a list of neighbor nodes.
               - get_edge_cost(node1, node2): Returns the cost to move between two nodes.
               - nodes: A list or set of all nodes in the graph.
        heuristic_function: A function h(node, goal) that estimates the cost
                            from node to goal.
    Returns:
        A list representing the path from start_node to goal_node, or None if no path exists.
    '''

    # g_score: cost from start to current node
    # f_score: g_score + h_score (estimated total cost)
    g_score = {node: float('inf') for node in graph.nodes}
    f_score = {node: float('inf') for node in graph.nodes}
    parent = {} # To reconstruct the path

    # Initialize start node
    g_score[start_node] = 0
    f_score[start_node] = heuristic_function(start_node, goal_node)

    # Open list is a priority queue storing (f_score, node)
    open_list = [(f_score[start_node], start_node)]
    
    # Closed list stores nodes that have been fully evaluated
    closed_list = set()

    while open_list:
        # Get the node with the lowest f_score from the open list
        current_f, current_node = heapq.heappop(open_list)

        if current_node == goal_node:
            return reconstruct_path(parent, current_node) # Path found!

        # If we've already processed this node with a better or equal path, skip it
        if current_node in closed_list:
            continue

        closed_list.add(current_node)

        for neighbor in graph.get_neighbors(current_node):
            # If the neighbor is already in the closed list, ignore it
            if neighbor in closed_list:
                continue

            # Calculate tentative g_score for the neighbor
            # This is the cost from start to current_node + cost from current_node to neighbor
            tentative_g_score = g_score[current_node] + graph.get_edge_cost(current_node, neighbor)

            # If this path to neighbor is better than any previous one, record it
            if tentative_g_score < g_score[neighbor]:
                parent[neighbor] = current_node
                g_score[neighbor] = tentative_g_score
                f_score[neighbor] = g_score[neighbor] + heuristic_function(neighbor, goal_node)
                
                # Add or update the neighbor in the open list
                # heapq.heappush handles duplicates; the one with lower f_score will be processed first.
                heapq.heappush(open_list, (f_score[neighbor], neighbor))

    return None # No path found

def reconstruct_path(parent_map, current_node):
    '''Reconstructs the path from the start node to the current_node.'''
    path = [current_node]
    while current_node in parent_map:
        current_node = parent_map[current_node]
        path.append(current_node)
    return path[::-1] # Reverse to get path from start to goal
```

### 5. Uses and real-world implementations:
A* is a widely used algorithm due to its efficiency and optimality guarantees (with an admissible heuristic).

*   **Video Game AI (Pathfinding):** Used extensively in games for non-player characters (NPCs) to navigate game worlds, find routes to targets, or avoid obstacles. This is crucial in genres like real-time strategy (RTS), role-playing games (RPGs), and even first-person shooters for enemy movement.
*   **Robotics (Motion Planning):** Robots use A* to plan collision-free paths in complex, dynamic environments. This applies to industrial robots in manufacturing, autonomous vehicles navigating city streets, and even drones performing aerial inspections.
*   **Logistics and Transportation (Route Optimization):** Finding the shortest or fastest routes for delivery services (e.g., Amazon, UPS), ride-sharing apps (e.g., Uber, Lyft), and public transportation networks, considering factors like traffic, road closures, and travel time.
"""

canvas_payload = r"""
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0d111a);
scene.fog = new THREE.FogExp2(0x0d111a, 0.032);

const camera = new THREE.PerspectiveCamera(52, window.innerWidth / window.innerHeight, 0.1, 500);
camera.position.set(0, 10, 24);
camera.lookAt(0, 0, 0);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.body.style.margin = '0';
document.body.style.overflow = 'hidden';
document.body.style.background = '#0d111a';
document.body.appendChild(renderer.domElement);
renderer.domElement.style.position = 'fixed';
renderer.domElement.style.top = '0';
renderer.domElement.style.left = '0';
renderer.domElement.style.zIndex = '0';

const controls = new window.OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.minDistance = 7;
controls.maxDistance = 55;
controls.maxPolarAngle = Math.PI * 0.84;

const ambient = new THREE.AmbientLight(0x10182e, 2.2);
scene.add(ambient);
const keyLight = new THREE.PointLight(0x3366ff, 3.2, 65);
keyLight.position.set(5, 14, 8);
keyLight.castShadow = true;
scene.add(keyLight);
const fillLight = new THREE.PointLight(0xaa44ff, 1.8, 45);
fillLight.position.set(-10, 5, -5);
scene.add(fillLight);
const rimLight = new THREE.PointLight(0x00ffcc, 1.0, 38);
rimLight.position.set(2, -5, -12);
scene.add(rimLight);

const gridHelper = new THREE.GridHelper(44, 32, 0x151d32, 0x0d1222);
gridHelper.position.y = -4.5;
scene.add(gridHelper);

const NODE_DEFS = [
  { id: 'S', pos: new THREE.Vector3(-8,  0.5,  2.0), h: 10 },
  { id: 'A', pos: new THREE.Vector3(-4,  3.5, -2.5), h: 7  },
  { id: 'B', pos: new THREE.Vector3(-4, -1.5,  3.5), h: 6  },
  { id: 'C', pos: new THREE.Vector3( 0,  4.5, -1.0), h: 4  },
  { id: 'D', pos: new THREE.Vector3( 0,  0.0,  4.0), h: 5  },
  { id: 'E', pos: new THREE.Vector3( 3,  2.5, -3.0), h: 2  },
  { id: 'F', pos: new THREE.Vector3( 4, -1.5,  1.5), h: 3  },
  { id: 'G', pos: new THREE.Vector3( 8,  1.0, -1.0), h: 0  },
];

const EDGE_DEFS = [
  { from: 'S', to: 'A', w: 3 },
  { from: 'S', to: 'B', w: 2 },
  { from: 'A', to: 'C', w: 4 },
  { from: 'A', to: 'D', w: 6 },
  { from: 'B', to: 'D', w: 3 },
  { from: 'B', to: 'F', w: 5 },
  { from: 'C', to: 'E', w: 2 },
  { from: 'C', to: 'F', w: 7 },
  { from: 'D', to: 'E', w: 4 },
  { from: 'D', to: 'F', w: 2 },
  { from: 'E', to: 'G', w: 3 },
  { from: 'F', to: 'G', w: 4 },
];

const adjacency = {};
NODE_DEFS.forEach(n => (adjacency[n.id] = []));
EDGE_DEFS.forEach(e => {
  adjacency[e.from].push({ to: e.to, w: e.w });
  adjacency[e.to].push({ to: e.from, w: e.w });
});

const heuristic = {};
NODE_DEFS.forEach(n => (heuristic[n.id] = n.h));

const C = {
  UNVISITED: 0x1e2d48,
  START:     0x00ccff,
  GOAL:      0xffdd00,
  OPEN:      0x0099ff,
  CURRENT:   0xffcc00,
  CLOSED:    0xaa22ee,
  PATH:      0x00ff66,
  EDGE_DEF:  0x111d30,
  EDGE_ACT:  0xffcc00,
  EDGE_PATH: 0x00ff66,
  EDGE_OPEN: 0x0077cc,
};

const nodeMeshes = {};
const nodeGlows  = {};
const nodeRings  = {};

NODE_DEFS.forEach(n => {
  const radius = (n.id === 'S' || n.id === 'G') ? 0.78 : 0.62;
  const geo  = new THREE.SphereGeometry(radius, 48, 48);
  const mat  = new THREE.MeshPhongMaterial({
    color: n.id === 'S' ? C.START : (n.id === 'G' ? C.GOAL : C.UNVISITED),
    emissive: 0x060a14, shininess: 130, specular: 0x6688cc
  });
  const mesh = new THREE.Mesh(geo, mat);
  mesh.position.copy(n.pos);
  mesh.castShadow = true;
  mesh.userData.id = n.id;
  scene.add(mesh);
  nodeMeshes[n.id] = mesh;

  const glowGeo = new THREE.SphereGeometry(radius * 1.55, 32, 32);
  const glowMat = new THREE.MeshBasicMaterial({ color: C.UNVISITED, transparent: true, opacity: 0.05, side: THREE.BackSide });
  const glow = new THREE.Mesh(glowGeo, glowMat);
  glow.position.copy(n.pos);
  scene.add(glow);
  nodeGlows[n.id] = glow;

  const ringGeo = new THREE.RingGeometry(radius * 1.25, radius * 1.45, 48);
  const ringMat = new THREE.MeshBasicMaterial({ color: C.UNVISITED, transparent: true, opacity: 0.0, side: THREE.DoubleSide });
  const ring = new THREE.Mesh(ringGeo, ringMat);
  ring.position.copy(n.pos);
  ring.lookAt(camera.position);
  scene.add(ring);
  nodeRings[n.id] = ring;
});

const edgeMeshes = [];
EDGE_DEFS.forEach(e => {
  const fPos = NODE_DEFS.find(n => n.id === e.from).pos;
  const tPos = NODE_DEFS.find(n => n.id === e.to).pos;
  const geo  = new THREE.BufferGeometry().setFromPoints([fPos.clone(), tPos.clone()]);
  const mat  = new THREE.LineBasicMaterial({ color: C.EDGE_DEF, transparent: true, opacity: 0.45 });
  const line = new THREE.Line(geo, mat);
  scene.add(line);
  const mid = new THREE.Vector3().addVectors(fPos, tPos).multiplyScalar(0.5);
  edgeMeshes.push({ line, mat, from: e.from, to: e.to, w: e.w, mid });
});

const FONT = "'Courier New','Lucida Console',monospace";
const PANEL = `position:fixed;z-index:100;backdrop-filter:blur(12px);
  background:rgba(6,9,20,0.90);border:1px solid rgba(60,100,220,0.22);border-radius:14px;
  font-family:${FONT};color:#a8c0e8;`;

function el(tag, css, html) {
  const d = document.createElement(tag);
  if (css)  d.style.cssText = css;
  if (html) d.innerHTML = html;
  document.body.appendChild(d);
  return d;
}

const infoPanel = el('div',
  `${PANEL}top:14px;left:50%;transform:translateX(-50%);
   max-width:700px;width:calc(100% - 320px);padding:14px 22px;
   font-size:13px;line-height:1.7;box-shadow:0 0 44px rgba(30,80,255,0.16);`
);

const sidePanel = el('div',
  `${PANEL}top:14px;right:14px;width:210px;padding:14px 16px;
   font-size:12px;line-height:1.7;box-shadow:0 0 28px rgba(30,80,255,0.12);max-height:calc(100vh - 110px);overflow-y:auto;`
);

const ctrlPanel = el('div',
  `${PANEL}bottom:18px;left:50%;transform:translateX(-50%);
   display:flex;align-items:center;gap:10px;padding:10px 22px;
   box-shadow:0 0 44px rgba(30,80,255,0.2);white-space:nowrap;`
);

const BTN = `background:linear-gradient(135deg,#0c1530,#080e22);
  border:1px solid rgba(70,120,240,0.38);color:#7899dd;border-radius:8px;
  padding:7px 15px;cursor:pointer;font-family:${FONT};font-size:12.5px;transition:border-color 0.2s,color 0.2s;`;

function mkBtn(lbl) {
  const b = document.createElement('button');
  b.innerHTML = lbl;
  b.style.cssText = BTN;
  b.onmouseenter = () => { b.style.borderColor = 'rgba(100,160,255,0.8)'; b.style.color = '#ccdeff'; };
  b.onmouseleave = () => { b.style.borderColor = 'rgba(70,120,240,0.38)';  b.style.color = '#7899dd'; };
  ctrlPanel.appendChild(b);
  return b;
}

const nextBtn    = mkBtn('&#9654; Next Step');
const autoBtn    = mkBtn('&#9654;&#9654; Auto Play');
const restartBtn = mkBtn('&#8635; Restart');

const spLbl = document.createElement('span');
spLbl.style.cssText = `color:#2e4466;font-family:${FONT};font-size:12px;margin-left:4px;`;
spLbl.textContent = 'Speed:';
ctrlPanel.appendChild(spLbl);
const speedSlider = document.createElement('input');
speedSlider.type = 'range'; speedSlider.min = '1'; speedSlider.max = '10'; speedSlider.value = '5';
speedSlider.style.cssText = 'width:80px;accent-color:#3366ff;cursor:pointer;';
ctrlPanel.appendChild(speedSlider);

el('div',
  `${PANEL}bottom:18px;left:14px;padding:12px 16px;font-size:12px;line-height:2.1;`,
  `<div style="color:#2a3a5a;font-size:11px;letter-spacing:1px;margin-bottom:2px">LEGEND</div>
   <div><span style="color:#00ccff;font-size:16px">&#11044;</span> Start (S)</div>
   <div><span style="color:#ffdd00;font-size:16px">&#11044;</span> Goal (G)</div>
   <div><span style="color:#1e2d48;font-size:16px">&#11044;</span> Unvisited</div>
   <div><span style="color:#0099ff;font-size:16px">&#11044;</span> Open List (frontier)</div>
   <div><span style="color:#ffcc00;font-size:16px">&#11044;</span> Current node</div>
   <div><span style="color:#aa22ee;font-size:16px">&#11044;</span> Closed List (done)</div>
   <div><span style="color:#00ff66;font-size:16px">&#11044;</span> Final path</div>`
);

const tooltip = el('div',
  `position:fixed;z-index:200;display:none;pointer-events:none;
   background:rgba(5,8,20,0.95);border:1px solid rgba(70,140,255,0.5);
   border-radius:10px;padding:10px 15px;font-family:${FONT};font-size:12px;
   color:#99bbee;box-shadow:0 0 22px rgba(40,90,255,0.32);line-height:1.8;`
);

const nodeLabels = {};
NODE_DEFS.forEach(n => {
  const d = document.createElement('div');
  d.style.cssText = `position:fixed;pointer-events:none;z-index:50;
    color:#ffffff;font-family:${FONT};font-size:14px;font-weight:bold;
    text-shadow:0 0 10px #3366ff,0 0 24px #3366ff,0 0 44px #1133aa;
    transform:translate(-50%,-50%);transition:color 0.3s;`;
  d.textContent = n.id;
  document.body.appendChild(d);
  nodeLabels[n.id] = d;
});

const hLabels = {};
NODE_DEFS.forEach(n => {
  const d = document.createElement('div');
  d.style.cssText = `position:fixed;pointer-events:none;z-index:49;
    color:#556688;font-family:${FONT};font-size:10px;
    transform:translate(-50%,-50%);`;
  d.textContent = 'h=' + n.h;
  document.body.appendChild(d);
  hLabels[n.id] = d;
});

const weightLabels = [];
edgeMeshes.forEach(e => {
  const d = document.createElement('div');
  d.textContent = e.w;
  d.style.cssText = `position:fixed;pointer-events:none;z-index:49;
    color:#3a5070;font-family:${FONT};font-size:10.5px;transform:translate(-50%,-50%);`;
  document.body.appendChild(d);
  weightLabels.push({ d, mid: e.mid });
});

const progressWrap = el('div',
  `${PANEL}bottom:78px;left:50%;transform:translateX(-50%);padding:6px 22px 9px;min-width:280px;`
);
const progressLabel = document.createElement('div');
progressLabel.style.cssText = `font-family:${FONT};font-size:11px;color:#2a3f66;text-align:center;margin-bottom:4px;`;
progressLabel.textContent = 'Step 0 / 0';
const progressTrack = document.createElement('div');
progressTrack.style.cssText = `height:4px;border-radius:2px;background:rgba(255,255,255,0.06);overflow:hidden;`;
const progressBar = document.createElement('div');
progressBar.style.cssText = `height:100%;width:0%;background:linear-gradient(90deg,#1133bb,#3366ff);border-radius:2px;transition:width 0.3s;`;
progressTrack.appendChild(progressBar);
progressWrap.appendChild(progressLabel);
progressWrap.appendChild(progressTrack);

function generateSteps() {
  const steps = [];
  const gCost = {};
  const parent = {};
  NODE_DEFS.forEach(n => { gCost[n.id] = Infinity; parent[n.id] = null; });
  gCost['S'] = 0;

  let openSet  = new Set(['S']);
  let closedSet = new Set();
  const openMap = { 'S': { g: 0, h: heuristic['S'], f: heuristic['S'] } };
  let pathEdges = new Set();
  let pathNodes = new Set();

  steps.push({
    type: 'init', current: null, neighbors: [], activeEdges: new Set(),
    open: { ...openMap }, closed: new Set(closedSet), path: new Set(pathNodes), pathEdges: new Set(pathEdges),
    gCost: { ...gCost },
    msg: `&#128640; <b style="color:#88aaff">Initialization.</b> Start node <b style="color:#00ccff">S</b> added to Open List.
          &nbsp; g(S)=<b>0</b>, h(S)=<b>${heuristic['S']}</b>, f(S)=<b>${heuristic['S']}</b>.
          A* expands nodes in order of lowest f = g + h.`
  });

  let safeGuard = 0;
  while (openSet.size > 0 && safeGuard++ < 200) {
    let current = null, minF = Infinity;
    openSet.forEach(id => { if (openMap[id].f < minF) { minF = openMap[id].f; current = id; } });
    if (!current) break;

    if (current === 'G') {
      let n = 'G'; pathNodes = new Set();
      while (n) { pathNodes.add(n); n = parent[n]; }
      let n2 = 'G';
      while (parent[n2]) {
        pathEdges.add([n2, parent[n2]].sort().join('|'));
        n2 = parent[n2];
      }
      steps.push({
        type: 'goal', current, neighbors: [], activeEdges: new Set(),
        open: { ...openMap }, closed: new Set(closedSet), path: new Set(pathNodes), pathEdges: new Set(pathEdges),
        gCost: { ...gCost },
        msg: `&#127937; <b style="color:#88aaff">Goal reached!</b> Node <b style="color:#ffdd00">G</b> dequeued from Open List.
              Total path cost = <b style="color:#00ff66">${gCost['G']}</b>. Reconstructing shortest path...`
      });
      break;
    }

    const curData = openMap[current];
    openSet.delete(current);
    delete openMap[current];
    closedSet.add(current);

    steps.push({
      type: 'pick', current, neighbors: [], activeEdges: new Set(),
      open: { ...openMap }, closed: new Set(closedSet), path: new Set(pathNodes), pathEdges: new Set(pathEdges),
      gCost: { ...gCost },
      msg: `&#128205; <b style="color:#88aaff">Dequeue minimum-f node.</b>
            Node <b style="color:#ffcc00">${current}</b>: &nbsp;
            f(<b>${current}</b>) = g(<b>${curData.g}</b>) + h(<b>${curData.h}</b>) = <b>${curData.f}</b>.
            Moved to <b style="color:#bb55ff">Closed List</b>. Exploring neighbors...`
    });

    const nbrs = adjacency[current];
    const activeEdges = new Set();
    const neighborIds = [];

    nbrs.forEach(({ to, w }) => {
      if (closedSet.has(to)) return;
      const tentG  = gCost[current] + w;
      const h      = heuristic[to];
      const f      = tentG + h;
      const eKey   = [current, to].sort().join('|');
      const oldG   = gCost[to];
      const improved = tentG < oldG;
      const oldF   = oldG === Infinity ? '∞' : (oldG + h);
      activeEdges.add(eKey);
      neighborIds.push(to);

      if (improved) {
        gCost[to]   = tentG;
        parent[to]  = current;
        openSet.add(to);
        openMap[to] = { g: tentG, h, f };
      }

      steps.push({
        type: 'relax', current, neighbors: [to], activeEdges: new Set([eKey]),
        open: { ...openMap }, closed: new Set(closedSet), path: new Set(pathNodes), pathEdges: new Set(pathEdges),
        gCost: { ...gCost },
        msg: improved
          ? `&#128270; <b style="color:#88aaff">Relaxing edge</b>
             <b style="color:#ffcc00">${current}</b>&#8594;<b style="color:#33bbff">${to}</b> (cost ${w}).
             &nbsp; f(<b>${to}</b>) = g(<b>${tentG}</b>) + h(<b>${h}</b>) = <b style="color:#44ff99">${f}</b>.
             &nbsp; &#9989; Improved from ${oldF}. <b>${to}</b> updated in Open List.`
          : `&#128270; <b style="color:#88aaff">Checking edge</b>
             <b style="color:#ffcc00">${current}</b>&#8594;<b style="color:#33bbff">${to}</b> (cost ${w}).
             &nbsp; f(<b>${to}</b>) = g(<b>${tentG}</b>) + h(<b>${h}</b>) = <b>${f}</b>.
             &nbsp; &#10060; Not better than current best (${oldF}). Skipped.`
      });
    });
  }

  if (openSet.size === 0 && !steps.find(s => s.type === 'goal')) {
    steps.push({
      type: 'no_path', current: null, neighbors: [], activeEdges: new Set(),
      open: {}, closed: new Set(closedSet), path: new Set(), pathEdges: new Set(),
      gCost: { ...gCost },
      msg: `&#9888;&#65039; <b style="color:#ff4444">No path found.</b> Open List is empty. Goal G is unreachable from S.`
    });
  }

  return steps;
}

function applyStep(step) {
  NODE_DEFS.forEach(n => {
    let col;
    if (step.path.has(n.id))         col = n.id === 'G' ? C.GOAL : (n.id === 'S' ? C.START : C.PATH);
    else if (n.id === step.current)  col = C.CURRENT;
    else if (step.neighbors.includes(n.id)) col = C.OPEN;
    else if (step.closed.has(n.id))  col = C.CLOSED;
    else if (step.open[n.id])        col = C.OPEN;
    else if (n.id === 'S')           col = C.START;
    else if (n.id === 'G')           col = C.GOAL;
    else                             col = C.UNVISITED;

    const mesh = nodeMeshes[n.id];
    const glow = nodeGlows[n.id];
    const ring = nodeRings[n.id];
    mesh.material.color.setHex(col);
    const emHex = col === C.UNVISITED ? 0x040810 : col;
    mesh.material.emissive.setHex(emHex);
    mesh.material.emissiveIntensity = col === C.UNVISITED ? 0.04 : 0.25;
    glow.material.color.setHex(col);
    glow.material.opacity = col === C.UNVISITED ? 0.04 : 0.20;
    const isActive = (n.id === step.current || step.neighbors.includes(n.id));
    ring.material.color.setHex(col);
    ring.material.opacity = isActive ? 0.60 : (step.open[n.id] ? 0.25 : 0.0);
  });

  edgeMeshes.forEach(e => {
    const eKey = [e.from, e.to].sort().join('|');
    let col = C.EDGE_DEF, opa = 0.35;
    if (step.pathEdges.has(eKey))          { col = C.EDGE_PATH; opa = 1.0; }
    else if (step.activeEdges.has(eKey))   { col = C.EDGE_ACT;  opa = 1.0; }
    else if (step.open[e.from] || step.open[e.to]) { col = C.EDGE_OPEN; opa = 0.5; }
    e.mat.color.setHex(col);
    e.mat.opacity = opa;
  });

  infoPanel.innerHTML =
    `<span style="color:#2a3f6a;font-size:11px;letter-spacing:1px">A* SEARCH ALGORITHM</span>
     &nbsp;&nbsp;<span style="color:#1e2e4a;font-size:11px">Step ${stepIndex + 1} / ${steps.length}</span>
     <br/><span style="font-size:13px">${step.msg}</span>`;

  let openRows = '', closedRows = '';
  const openEntries = Object.entries(step.open).sort((a, b) => a[1].f - b[1].f);
  openEntries.forEach(([id, data]) => {
    openRows += `<div style="display:flex;justify-content:space-between;gap:8px;line-height:1.85;border-bottom:1px solid rgba(30,50,90,0.4);padding:1px 0">
      <span style="color:#33aaff;font-weight:bold">${id}</span>
      <span style="color:#2a4470">g=<b style="color:#6699cc">${data.g}</b></span>
      <span style="color:#2a4470">h=<b style="color:#6699cc">${data.h}</b></span>
      <span style="color:#3355aa">f=<b style="color:#88aaff">${data.f}</b></span>
    </div>`;
  });
  step.closed.forEach(id => {
    const g = step.gCost[id];
    const h = heuristic[id];
    closedRows += `<div style="display:flex;justify-content:space-between;gap:8px;line-height:1.85;border-bottom:1px solid rgba(30,20,50,0.4);padding:1px 0">
      <span style="color:#9944cc;font-weight:bold">${id}</span>
      <span style="color:#2a1a44">g=<b style="color:#7744aa">${g}</b></span>
      <span style="color:#2a1a44">h=<b style="color:#7744aa">${h}</b></span>
      <span style="color:#441a88">f=<b style="color:#9966cc">${g === Infinity ? '∞' : g + h}</b></span>
    </div>`;
  });
  sidePanel.innerHTML =
    `<div style="color:#1e3060;font-size:11px;letter-spacing:1px;margin-bottom:8px">LISTS</div>
     <div style="color:#1e4488;font-size:11px;margin-bottom:4px;letter-spacing:0.5px">&#9654; OPEN  <span style="float:right;color:#112244">${openEntries.length} nodes</span></div>
     ${openRows || '<div style="color:#1a2a44;font-size:11px">Empty</div>'}
     <div style="color:#441866;font-size:11px;margin:10px 0 4px;letter-spacing:0.5px">&#9654; CLOSED  <span style="float:right;color:#221133">${step.closed.size} nodes</span></div>
     ${closedRows || '<div style="color:#1a1030;font-size:11px">Empty</div>'}`;

  const pct = steps.length > 1 ? (stepIndex / (steps.length - 1)) * 100 : 0;
  progressBar.style.width = pct + '%';
  progressLabel.textContent = `Step ${stepIndex + 1} / ${steps.length}`;
}

let steps     = [];
let stepIndex = 0;
let isPlaying = false;
let playTimer = null;

function initAlgo() {
  steps     = generateSteps();
  stepIndex = 0;
  applyStep(steps[0]);
}

function doNext() {
  if (stepIndex < steps.length - 1) { stepIndex++; applyStep(steps[stepIndex]); }
  else stopPlay();
}

function stopPlay() {
  isPlaying = false;
  if (playTimer) { clearTimeout(playTimer); playTimer = null; }
  autoBtn.innerHTML = '&#9654;&#9654; Auto Play';
}

function startPlay() {
  isPlaying = true;
  autoBtn.innerHTML = '&#9646;&#9646; Pause';
  function tick() {
    if (!isPlaying) return;
    if (stepIndex < steps.length - 1) {
      doNext();
      const delay = Math.round(1600 - parseInt(speedSlider.value) * 140);
      playTimer = setTimeout(tick, delay);
    } else stopPlay();
  }
  playTimer = setTimeout(tick, Math.round(1600 - parseInt(speedSlider.value) * 140));
}

nextBtn.addEventListener('click',    () => { stopPlay(); doNext();    });
restartBtn.addEventListener('click', () => { stopPlay(); initAlgo(); });
autoBtn.addEventListener('click',    () => { isPlaying ? stopPlay() : startPlay(); });

const raycaster = new THREE.Raycaster();
const mouse     = new THREE.Vector2(-9999, -9999);

window.addEventListener('mousemove', e => {
  mouse.x =  (e.clientX / window.innerWidth)  * 2 - 1;
  mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
  tooltip.style.left = (e.clientX + 16) + 'px';
  tooltip.style.top  = (e.clientY - 14) + 'px';
});

function project(pos3d) {
  const v = pos3d.clone().project(camera);
  return {
    x: ( v.x * 0.5 + 0.5) * window.innerWidth,
    y: (-v.y * 0.5 + 0.5) * window.innerHeight,
    behind: v.z > 1.0
  };
}

const clock = new THREE.Clock();

function animate() {
  requestAnimationFrame(animate);
  const t = clock.getElapsedTime();
  controls.update();

  NODE_DEFS.forEach((n, i) => {
    const mesh = nodeMeshes[n.id];
    const glow = nodeGlows[n.id];
    const ring = nodeRings[n.id];
    ring.lookAt(camera.position);

    const col      = mesh.material.color.getHex();
    const isActive = (col === C.CURRENT || col === C.OPEN);
    const floatY   = n.pos.y + Math.sin(t * 0.75 + i * 1.2) * 0.05;

    if (isActive) {
      const pulse = 1 + 0.1 * Math.sin(t * 5.5);
      mesh.scale.setScalar(pulse);
      glow.scale.setScalar(pulse * 1.1);
      ring.scale.setScalar(1 + 0.14 * Math.sin(t * 3.8 + 0.4));
    } else {
      mesh.scale.setScalar(col === C.PATH ? 1.08 : 1.0);
      glow.scale.setScalar(1.0);
      ring.scale.setScalar(1.0);
    }

    mesh.position.y = floatY;
    glow.position.y = floatY;
    ring.position.y = floatY;
  });

  keyLight.position.x  =  5 + Math.sin(t * 0.28) * 2.0;
  keyLight.position.z  =  8 + Math.cos(t * 0.22) * 2.0;
  fillLight.position.x = -10 + Math.cos(t * 0.20) * 1.5;

  raycaster.setFromCamera(mouse, camera);
  const meshArr = NODE_DEFS.map(n => nodeMeshes[n.id]);
  const hits    = raycaster.intersectObjects(meshArr);
  if (hits.length > 0) {
    const id   = hits[0].object.userData.id;
    const step = steps[stepIndex] || {};
    const g    = (step.gCost && step.gCost[id] !== undefined) ? step.gCost[id] : '—';
    const h    = heuristic[id];
    const gNum = (typeof g === 'number' && g !== Infinity) ? g : null;
    const fStr = gNum !== null ? (gNum + h) : (g === Infinity ? '∞' : '—');
    const gStr = g === Infinity ? '∞' : g;
    tooltip.style.display = 'block';
    tooltip.innerHTML =
      `<b style="color:#88aaff;font-size:13px">Node ${id}</b><br>
       g (cost from S):&nbsp; <b style="color:#55ccff">${gStr}</b><br>
       h (heuristic to G): <b style="color:#ffbb44">${h}</b><br>
       f = g + h:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b style="color:#66ff99">${fStr}</b>`;
  } else {
    tooltip.style.display = 'none';
  }

  NODE_DEFS.forEach(n => {
    const p = project(nodeMeshes[n.id].position);
    const lbl = nodeLabels[n.id];
    const hlbl = hLabels[n.id];
    if (p.behind) { lbl.style.display = 'none'; hlbl.style.display = 'none'; return; }
    lbl.style.display  = 'block';
    lbl.style.left     = p.x + 'px';
    lbl.style.top      = (p.y - 28) + 'px';
    hlbl.style.display = 'block';
    hlbl.style.left    = p.x + 'px';
    hlbl.style.top     = (p.y + 22) + 'px';
  });

  weightLabels.forEach(w => {
    const p = project(w.mid);
    if (p.behind) { w.d.style.display = 'none'; return; }
    w.d.style.display = 'block';
    w.d.style.left    = p.x + 'px';
    w.d.style.top     = p.y + 'px';
  });

  renderer.render(scene, camera);
}

window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

initAlgo();
animate();
"""

def get_astar_content():
    # TODO: PASTE 10-QUESTION QUIZ JSON HERE
    quiz_payload = [
    {
        "question": "Which two algorithms does the A* search algorithm combine features of?",
        "options": [
            "Breadth-First Search and Depth-First Search",
            "Dijkstra's Algorithm and Greedy Best-First Search",
            "Bellman-Ford and Prim's Algorithm",
            "Kruskal's Algorithm and Floyd-Warshall"
        ],
        "correct_index": 1,
        "explanation": "A* combines Dijkstra's focus on exact past costs with Greedy Best-First Search's heuristic estimates for future costs."
    },
    {
        "question": "In the A* evaluation function f(n) = g(n) + h(n), what does g(n) represent?",
        "options": [
            "The total estimated cost to the goal",
            "The heuristic estimated cost to go",
            "The actual cost from the starting node to the current node",
            "The number of nodes in the open list"
        ],
        "correct_index": 2,
        "explanation": "g(n) is the 'past cost' or 'cost so far' to reach the current node n from the starting node."
    },
    {
        "question": "For A* to guarantee finding the shortest path, the heuristic function h(n) must be 'admissible'. What does this mean?",
        "options": [
            "It never underestimates the true cost to the goal.",
            "It never overestimates the true cost to the goal.",
            "It must exactly equal the true cost to the goal.",
            "It must be calculated using Manhattan distance."
        ],
        "correct_index": 1,
        "explanation": "An admissible heuristic is optimistic; it never overestimates the true cost to reach the goal."
    },
    {
        "question": "What is the primary purpose of the 'Closed List' in A*?",
        "options": [
            "To prioritize which nodes to explore next.",
            "To store nodes that are currently being evaluated.",
            "To store the final shortest path.",
            "To store nodes that have already been fully explored."
        ],
        "correct_index": 3,
        "explanation": "The Closed List holds nodes whose neighbors have all been processed, ensuring the algorithm doesn't waste time revisiting them."
    },
    {
        "question": "How does A* select the very next node to explore from the Open List?",
        "options": [
            "It picks the node with the lowest g(n) value.",
            "It picks the node with the lowest h(n) value.",
            "It picks the node with the lowest f(n) value.",
            "It picks the node that was added most recently."
        ],
        "correct_index": 2,
        "explanation": "A* is a 'best-first' search, meaning it always prioritizes exploring the node with the lowest total estimated cost, f(n)."
    },
    {
        "question": "When evaluating a neighbor node, under what condition does A* update that neighbor's g(n) value?",
        "options": [
            "Only if the neighbor is already in the Closed List.",
            "If the new g(n) is lower than its previously recorded g(n) value.",
            "Every single time the neighbor is evaluated.",
            "If the new g(n) is higher than its previously recorded g(n) value."
        ],
        "correct_index": 1,
        "explanation": "The g value is updated only if the algorithm discovers a faster (lower cost) path to reach that neighbor."
    },
    {
        "question": "In the provided 4x4 grid example, which heuristic function is used to estimate the cost to the goal?",
        "options": [
            "Euclidean distance",
            "Chebyshev distance",
            "Manhattan distance",
            "Minkowski distance"
        ],
        "correct_index": 2,
        "explanation": "The example calculates the distance by adding the absolute differences of the x and y coordinates, which is the Manhattan distance."
    },
    {
        "question": "In the provided Python code implementation, what data structure is used to manage the Open List efficiently?",
        "options": [
            "A standard array",
            "A dictionary",
            "A priority queue (heapq)",
            "A linked list"
        ],
        "correct_index": 2,
        "explanation": "A priority queue (using the heapq library) is used to automatically keep the node with the lowest f_score at the front for quick extraction."
    },
    {
        "question": "Once the goal node is reached, how does the algorithm reconstruct the final shortest path?",
        "options": [
            "By sorting the Closed List alphabetically.",
            "By backtracking parent pointers from the goal node to the start node.",
            "By moving forward from the start node selecting lowest h(n) values.",
            "By printing the entire Open List."
        ],
        "correct_index": 1,
        "explanation": "Every time a node is successfully updated, its 'parent' is recorded. The final path is found by tracing these parents backward from the goal."
    },
    {
        "question": "According to the text, which of the following is a real-world implementation of the A* algorithm?",
        "options": [
            "Sorting large databases",
            "Encrypting passwords",
            "Video Game AI (Pathfinding)",
            "Compressing image files"
        ],
        "correct_index": 2,
        "explanation": "A* is heavily used in game development for NPC pathfinding to navigate game worlds and avoid obstacles."
    }
]

    return {
        "title": "A* Search Algorithm",
        "text_explanation": text_content,
        "media_type": "python_code",
        "code": canvas_payload,
        "quiz_data": quiz_payload
    }
