# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is Greedy Algorithms Algorithm?
➔ Greedy algorithms make the locally optimal choice at each stage with the hope of finding a global optimum.

### 2. Explanation:
A greedy algorithm works by making a series of choices. At each step, it picks the best immediate option available without considering the long-term consequences of that choice. It doesn't look ahead to see if a slightly worse immediate choice might lead to a much better overall solution. Instead, it focuses solely on maximizing or minimizing the current step's outcome. This "take what you can get now" approach makes greedy algorithms often simpler and faster than other optimization techniques, but it doesn't always guarantee the absolute best (globally optimal) solution. However, for many problems, a greedy strategy does yield the optimal solution, or at least a very good approximation.

### 3. Example:
Let's consider a **Smart Stock Replenishment System** for a retail store with a limited budget. The goal is to maximize the potential profit from restocking items.

**Scenario:**
You have a budget of **$30** to restock items. Each item has a specific cost and a projected profit if sold. Your greedy strategy is to prioritize items that offer the highest **profit per dollar spent** until your budget runs out.

**Available Items for Replenishment:**

```text
---------------------------------------------------
| Item | Cost ($) | Profit ($) |
---------------------------------------------------
| A    | 10       | 5          |
| B    | 20       | 12         |
| C    | 5        | 2          |
| D    | 15       | 9          |
| E    | 8        | 4.8        |
---------------------------------------------------
```

**Step-by-step Trace:**

1.  **Initial State:**
    ```text
    Budget: $30
    Selected Items for Replenishment: []
    Total Projected Profit: $0
    ```

2.  **Calculate Profit/Cost Ratio for each item:**
    This ratio helps us determine which item gives the most profit for each dollar invested.
    ```text
    ---------------------------------------------------
    | Item | Cost ($) | Profit ($) | Profit/Cost Ratio |
    ---------------------------------------------------
    | A    | 10       | 5          | 0.5  (5/10)       |
    | B    | 20       | 12         | 0.6  (12/20)      |
    | C    | 5        | 2          | 0.4  (2/5)        |
    | D    | 15       | 9          | 0.6  (9/15)       |
    | E    | 8        | 4.8        | 0.6  (4.8/8)      |
    ---------------------------------------------------
    ```

3.  **Sort Items by Profit/Cost Ratio (descending):**
    (Assuming tie-breaking by item name for items with the same ratio)
    ```text
    ---------------------------------------------------
    | Item | Cost ($) | Profit ($) | Profit/Cost Ratio |
    ---------------------------------------------------
    | B    | 20       | 12         | 0.6               |
    | D    | 15       | 9          | 0.6               |
    | E    | 8        | 4.8        | 0.6               |
    | A    | 10       | 5          | 0.5               |
    | C    | 5        | 2          | 0.4               |
    ---------------------------------------------------
    ```

4.  **Greedy Selection Process:**

    *   **Consider Item B (Ratio 0.6):**
        *   Current Budget: $30
        *   Item B Cost: $20
        *   Can we afford it? Yes ($30 >= $20).
        *   **Action:** Replenish Item B.
        ```text
        Budget: $30 - $20 = $10
        Selected Items: [Item B]
        Total Projected Profit: $0 + $12 = $12
        ```

    *   **Consider Item D (Ratio 0.6):**
        *   Current Budget: $10
        *   Item D Cost: $15
        *   Can we afford it? No ($10 < $15).
        *   **Action:** Skip Item D.

    *   **Consider Item E (Ratio 0.6):**
        *   Current Budget: $10
        *   Item E Cost: $8
        *   Can we afford it? Yes ($10 >= $8).
        *   **Action:** Replenish Item E.
        ```text
        Budget: $10 - $8 = $2
        Selected Items: [Item B, Item E]
        Total Projected Profit: $12 + $4.8 = $16.8
        ```

    *   **Consider Item A (Ratio 0.5):**
        *   Current Budget: $2
        *   Item A Cost: $10
        *   Can we afford it? No ($2 < $10).
        *   **Action:** Skip Item A.

    *   **Consider Item C (Ratio 0.4):**
        *   Current Budget: $2
        *   Item C Cost: $5
        *   Can we afford it? No ($2 < $5).
        *   **Action:** Skip Item C.

5.  **Final Result:**
    No more items can be replenished with the remaining budget.
    ```text
    Final Budget Remaining: $2
    Items Replenished: [Item B, Item E]
    Total Projected Profit from Replenishment: $16.8
    ```
    By making locally optimal choices (picking the item with the best profit/cost ratio at each step), the system maximizes the immediate profit given the budget constraint.

### 4. Algorithm Logic:

```python
def smart_stock_replenishment(items, budget):
    '''
    Optimizes stock replenishment using a greedy approach based on profit per unit cost.

    Args:
        items (list of dict): Each dict represents an item with 'name', 'cost', 'profit'.
        budget (float): The total budget available for replenishment.

    Returns:
        tuple: A tuple containing the list of selected items and the total profit generated.
    '''

    # 1. Calculate profit_per_cost ratio for each item
    #    and store it along with the item details.
    items_with_ratios = []
    for item in items:
        if item['cost'] > 0:
            profit_per_cost = item['profit'] / item['cost']
        else:
            profit_per_cost = float('inf') # Handle free items or items with no cost
        items_with_ratios.append({
            'name': item['name'],
            'cost': item['cost'],
            'profit': item['profit'],
            'profit_per_cost': profit_per_cost
        })

    # 2. Sort items based on profit_per_cost ratio in descending order.
    #    This is the greedy choice: prioritize items that yield the most profit per dollar.
    items_with_ratios.sort(key=lambda x: x['profit_per_cost'], reverse=True)

    selected_items = []
    total_profit = 0.0
    current_budget = budget

    # 3. Iterate through the sorted items and select them if affordable.
    for item in items_with_ratios:
        if current_budget >= item['cost']:
            selected_items.append(item['name'])
            current_budget -= item['cost']
            total_profit += item['profit']
        # If the current item cannot be afforded, we stop because subsequent items
        # (which have lower or equal profit_per_cost ratios) might also not be affordable
        # or we might not have enough budget to combine them effectively.
        # This is a simple greedy approach for the knapsack-like problem.
        # For fractional knapsack, we could take parts of items.
        # For 0/1 knapsack (which this is), this greedy choice is not always optimal
        # but is a common greedy heuristic.
        # In this specific stock replenishment context, it's a practical heuristic.

    return selected_items, total_profit

# Example Usage (as per the trace above):
# items_data = [
#     {'name': 'A', 'cost': 10, 'profit': 5},
#     {'name': 'B', 'cost': 20, 'profit': 12},
#     {'name': 'C', 'cost': 5, 'profit': 2},
#     {'name': 'D', 'cost': 15, 'profit': 9},
#     {'name': 'E', 'cost': 8, 'profit': 4.8},
# ]
# replenishment_budget = 30
# selected, profit = smart_stock_replenishment(items_data, replenishment_budget)
# print(f"Selected items: {selected}")
# print(f"Total profit: ${profit}")
```

### 5. Uses and real-world implementations:

*   **Minimum Spanning Tree Algorithms (Prim's and Kruskal's):** Used in network design to find the cheapest way to connect a set of nodes (e.g., laying fiber optic cables to connect cities) by iteratively choosing the locally cheapest edge that doesn't form a cycle.
*   **Dijkstra's Shortest Path Algorithm:** Finds the shortest path between two nodes in a graph with non-negative edge weights (e.g., GPS navigation systems finding the quickest route) by always extending the path through the unvisited neighbor with the smallest cumulative distance.
*   **Huffman Coding (Data Compression):** Used in file compression (like JPEG, MP3, ZIP) to create variable-length codes for characters, where more frequent characters get shorter codes, by repeatedly merging the two least frequent symbols.
"""

canvas_payload = r"""
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x1a0f14);
scene.fog = new THREE.FogExp2(0x1a0f14, 0.030);

const camera = new THREE.PerspectiveCamera(52, window.innerWidth / window.innerHeight, 0.1, 500);
camera.position.set(0, 10, 25);
camera.lookAt(0, 0, 0);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.body.style.margin = '0';
document.body.style.overflow = 'hidden';
document.body.style.background = '#1a0f14';
document.body.appendChild(renderer.domElement);
renderer.domElement.style.position = 'fixed';
renderer.domElement.style.top = '0';
renderer.domElement.style.left = '0';
renderer.domElement.style.zIndex = '0';

const controls = new window.OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.minDistance = 7;
controls.maxDistance = 55;
controls.maxPolarAngle = Math.PI * 0.84;

const ambient = new THREE.AmbientLight(0x1e0a12, 2.4);
scene.add(ambient);
const keyLight = new THREE.PointLight(0xff2266, 3.0, 65);
keyLight.position.set(5, 14, 8);
keyLight.castShadow = true;
scene.add(keyLight);
const fillLight = new THREE.PointLight(0x880033, 1.8, 50);
fillLight.position.set(-10, 5, -5);
scene.add(fillLight);
const rimLight = new THREE.PointLight(0xff6600, 1.2, 42);
rimLight.position.set(2, -5, -12);
scene.add(rimLight);

const gridHelper = new THREE.GridHelper(44, 32, 0x200a12, 0x160810);
gridHelper.position.y = -4.5;
scene.add(gridHelper);

// Graph designed so Greedy gets temporarily lured by a low-h dead-end (T),
// proving its sub-optimality vs A*. Optimal path: S->B->D->G (cost 2+3+4=9).
// Greedy picks S->A->C->T (trapped, h=1 but no edge to G), then backtracks
// to eventually find S->A->C->E->G, not necessarily the shortest route.
const NODE_DEFS = [
  { id: 'S', pos: new THREE.Vector3(-8.0,  0.5,  2.0), h: 9  },
  { id: 'A', pos: new THREE.Vector3(-3.5,  3.5, -2.0), h: 6  },
  { id: 'B', pos: new THREE.Vector3(-3.5, -1.5,  3.5), h: 7  },
  { id: 'C', pos: new THREE.Vector3( 0.5,  4.0,  0.5), h: 4  },
  { id: 'T', pos: new THREE.Vector3( 2.5,  5.5, -3.5), h: 1  },
  { id: 'D', pos: new THREE.Vector3( 0.5, -1.0,  4.0), h: 5  },
  { id: 'E', pos: new THREE.Vector3( 4.5,  2.5,  0.0), h: 3  },
  { id: 'G', pos: new THREE.Vector3( 8.0,  0.5, -1.5), h: 0  },
];

// Note: T has h=1 (looks great to Greedy) but ONLY connects back to C, so
// Greedy wastes steps going S->A->C->T, then must backtrack out.
const EDGE_DEFS = [
  { from: 'S', to: 'A', w: 5  },
  { from: 'S', to: 'B', w: 2  },
  { from: 'A', to: 'C', w: 6  },
  { from: 'A', to: 'D', w: 10 },
  { from: 'B', to: 'D', w: 3  },
  { from: 'B', to: 'E', w: 9  },
  { from: 'C', to: 'T', w: 4  },
  { from: 'C', to: 'E', w: 3  },
  { from: 'D', to: 'G', w: 4  },
  { from: 'D', to: 'E', w: 5  },
  { from: 'E', to: 'G', w: 2  },
];

const adjacency = {};
NODE_DEFS.forEach(n => (adjacency[n.id] = []));
EDGE_DEFS.forEach(e => {
  adjacency[e.from].push({ to: e.to, w: e.w });
  adjacency[e.to].push({ to: e.from, w: e.w });
});

const heuristic = {};
NODE_DEFS.forEach(n => (heuristic[n.id] = n.h));

const C = {
  UNVISITED: 0x2a1520,
  START:     0xff8800,
  GOAL:      0xffee00,
  OPEN:      0x9922cc,
  CURRENT:   0xff1166,
  CLOSED:    0x6a0a22,
  PATH:      0xff9900,
  EDGE_DEF:  0x1e0a10,
  EDGE_ACT:  0xff1166,
  EDGE_OPEN: 0x660099,
  EDGE_PATH: 0xff9900,
};

const nodeMeshes = {};
const nodeGlows  = {};
const nodeRings  = {};

NODE_DEFS.forEach(n => {
  const radius = (n.id === 'S' || n.id === 'G') ? 0.78 : (n.id === 'T' ? 0.56 : 0.62);
  const initCol = n.id === 'S' ? C.START : (n.id === 'G' ? C.GOAL : C.UNVISITED);
  const geo  = new THREE.SphereGeometry(radius, 48, 48);
  const mat  = new THREE.MeshPhongMaterial({
    color: initCol, emissive: 0x0a0408, shininess: 140, specular: 0xcc6688
  });
  const mesh = new THREE.Mesh(geo, mat);
  mesh.position.copy(n.pos);
  mesh.castShadow = true;
  mesh.userData.id = n.id;
  scene.add(mesh);
  nodeMeshes[n.id] = mesh;

  const glowGeo = new THREE.SphereGeometry(radius * 1.58, 32, 32);
  const glowMat = new THREE.MeshBasicMaterial({ color: initCol, transparent: true, opacity: 0.05, side: THREE.BackSide });
  const glow = new THREE.Mesh(glowGeo, glowMat);
  glow.position.copy(n.pos);
  scene.add(glow);
  nodeGlows[n.id] = glow;

  const ringGeo = new THREE.RingGeometry(radius * 1.28, radius * 1.48, 48);
  const ringMat = new THREE.MeshBasicMaterial({ color: initCol, transparent: true, opacity: 0.0, side: THREE.DoubleSide });
  const ring = new THREE.Mesh(ringGeo, ringMat);
  ring.position.copy(n.pos);
  ring.lookAt(camera.position);
  scene.add(ring);
  nodeRings[n.id] = ring;
});

const edgeMeshes = [];
EDGE_DEFS.forEach(e => {
  const fPos = NODE_DEFS.find(n => n.id === e.from).pos;
  const tPos = NODE_DEFS.find(n => n.id === e.to).pos;
  const geo  = new THREE.BufferGeometry().setFromPoints([fPos.clone(), tPos.clone()]);
  const mat  = new THREE.LineBasicMaterial({ color: C.EDGE_DEF, transparent: true, opacity: 0.40 });
  const line = new THREE.Line(geo, mat);
  scene.add(line);
  const mid = new THREE.Vector3().addVectors(fPos, tPos).multiplyScalar(0.5);
  edgeMeshes.push({ line, mat, from: e.from, to: e.to, w: e.w, mid });
});

const FONT = "'Courier New','Lucida Console',monospace";
const PANEL = `position:fixed;z-index:100;backdrop-filter:blur(12px);
  background:rgba(18,5,10,0.92);border:1px solid rgba(180,30,80,0.20);border-radius:14px;
  font-family:${FONT};color:#d0a0b0;`;

function el(tag, css, html) {
  const d = document.createElement(tag);
  if (css)  d.style.cssText = css;
  if (html) d.innerHTML = html;
  document.body.appendChild(d);
  return d;
}

const infoPanel = el('div',
  `${PANEL}top:14px;left:50%;transform:translateX(-50%);
   max-width:700px;width:calc(100% - 320px);padding:14px 22px;
   font-size:13px;line-height:1.7;box-shadow:0 0 44px rgba(200,20,60,0.14);`
);

const sidePanel = el('div',
  `${PANEL}top:14px;right:14px;width:210px;padding:14px 16px;
   font-size:12px;line-height:1.7;box-shadow:0 0 28px rgba(180,20,60,0.12);
   max-height:calc(100vh - 110px);overflow-y:auto;`
);

const ctrlPanel = el('div',
  `${PANEL}bottom:18px;left:50%;transform:translateX(-50%);
   display:flex;align-items:center;gap:10px;padding:10px 22px;
   box-shadow:0 0 44px rgba(200,20,60,0.18);white-space:nowrap;`
);

const BTN = `background:linear-gradient(135deg,#180810,#0e0508);
  border:1px solid rgba(200,40,80,0.35);color:#bb6688;border-radius:8px;
  padding:7px 15px;cursor:pointer;font-family:${FONT};font-size:12.5px;
  transition:border-color 0.2s,color 0.2s;`;

function mkBtn(lbl) {
  const b = document.createElement('button');
  b.innerHTML = lbl;
  b.style.cssText = BTN;
  b.onmouseenter = () => { b.style.borderColor = 'rgba(255,60,120,0.8)'; b.style.color = '#ffaabb'; };
  b.onmouseleave = () => { b.style.borderColor = 'rgba(200,40,80,0.35)';  b.style.color = '#bb6688'; };
  ctrlPanel.appendChild(b);
  return b;
}

const nextBtn    = mkBtn('&#9654; Next Step');
const autoBtn    = mkBtn('&#9654;&#9654; Auto Play');
const restartBtn = mkBtn('&#8635; Restart');

const spLbl = document.createElement('span');
spLbl.style.cssText = `color:#4a1a28;font-family:${FONT};font-size:12px;margin-left:4px;`;
spLbl.textContent = 'Speed:';
ctrlPanel.appendChild(spLbl);
const speedSlider = document.createElement('input');
speedSlider.type = 'range'; speedSlider.min = '1'; speedSlider.max = '10'; speedSlider.value = '5';
speedSlider.style.cssText = 'width:80px;accent-color:#cc2255;cursor:pointer;';
ctrlPanel.appendChild(speedSlider);

el('div',
  `${PANEL}bottom:18px;left:14px;padding:12px 16px;font-size:12px;line-height:2.1;`,
  `<div style="color:#3a1020;font-size:11px;letter-spacing:1px;margin-bottom:2px">LEGEND</div>
   <div><span style="color:#ff8800;font-size:16px">&#11044;</span> Start (S)</div>
   <div><span style="color:#ffee00;font-size:16px">&#11044;</span> Goal (G)</div>
   <div><span style="color:#2a1520;font-size:16px">&#11044;</span> Unvisited</div>
   <div><span style="color:#9922cc;font-size:16px">&#11044;</span> Open List (frontier)</div>
   <div><span style="color:#ff1166;font-size:16px">&#11044;</span> Current node</div>
   <div><span style="color:#6a0a22;font-size:16px">&#11044;</span> Closed List (visited)</div>
   <div><span style="color:#ff9900;font-size:16px">&#11044;</span> Final path</div>
   <div style="margin-top:6px;color:#3a1020;font-size:11px;letter-spacing:1px">NOTE</div>
   <div style="color:#442030;font-size:11px;line-height:1.5;max-width:150px">T has h=1 but<br>is a dead end!<br>Watch Greedy<br>get misled.</div>`
);

const tooltip = el('div',
  `position:fixed;z-index:200;display:none;pointer-events:none;
   background:rgba(14,4,8,0.96);border:1px solid rgba(200,40,80,0.50);
   border-radius:10px;padding:10px 15px;font-family:${FONT};font-size:12px;
   color:#cc8899;box-shadow:0 0 22px rgba(200,20,60,0.30);line-height:1.9;`
);

const nodeLabels = {};
NODE_DEFS.forEach(n => {
  const d = document.createElement('div');
  d.style.cssText = `position:fixed;pointer-events:none;z-index:50;
    color:#ffffff;font-family:${FONT};font-size:14px;font-weight:bold;
    text-shadow:0 0 10px #cc1144,0 0 24px #cc1144,0 0 44px #880022;
    transform:translate(-50%,-50%);transition:color 0.3s;`;
  d.textContent = n.id;
  document.body.appendChild(d);
  nodeLabels[n.id] = d;
});

const hLabels = {};
NODE_DEFS.forEach(n => {
  const d = document.createElement('div');
  d.style.cssText = `position:fixed;pointer-events:none;z-index:49;
    color:#663344;font-family:${FONT};font-size:10.5px;transform:translate(-50%,-50%);`;
  d.textContent = 'h=' + n.h;
  document.body.appendChild(d);
  hLabels[n.id] = d;
});

const weightLabels = [];
edgeMeshes.forEach(e => {
  const d = document.createElement('div');
  d.textContent = e.w;
  d.style.cssText = `position:fixed;pointer-events:none;z-index:49;
    color:#442030;font-family:${FONT};font-size:10.5px;transform:translate(-50%,-50%);`;
  document.body.appendChild(d);
  weightLabels.push({ d, mid: e.mid });
});

const progressWrap = el('div',
  `${PANEL}bottom:78px;left:50%;transform:translateX(-50%);padding:6px 22px 9px;min-width:280px;`
);
const progressLabel = document.createElement('div');
progressLabel.style.cssText = `font-family:${FONT};font-size:11px;color:#3a1020;text-align:center;margin-bottom:4px;`;
progressLabel.textContent = 'Step 0 / 0';
const progressTrack = document.createElement('div');
progressTrack.style.cssText = `height:4px;border-radius:2px;background:rgba(255,255,255,0.05);overflow:hidden;`;
const progressBar = document.createElement('div');
progressBar.style.cssText = `height:100%;width:0%;background:linear-gradient(90deg,#880022,#dd1155);border-radius:2px;transition:width 0.3s;`;
progressTrack.appendChild(progressBar);
progressWrap.appendChild(progressLabel);
progressWrap.appendChild(progressTrack);

// ─── Greedy Best-First Search Step Generator ─────────────────────────────────
function generateSteps() {
  const steps  = [];
  const parent = {};
  NODE_DEFS.forEach(n => { parent[n.id] = null; });

  let openSet   = new Set(['S']);
  let openMap   = { 'S': heuristic['S'] };
  let closedSet = new Set();
  let pathNodes = new Set();
  let pathEdges = new Set();

  steps.push({
    type: 'init', current: null, neighbors: [], activeEdge: null,
    open: { ...openMap }, closed: new Set(closedSet),
    path: new Set(pathNodes), pathEdges: new Set(pathEdges),
    msg: `&#128640; <b style="color:#ff88aa">Initialization.</b>
          Start node <b style="color:#ff8800">S</b> added to the Open List.
          h(S) = <b>${heuristic['S']}</b>.
          Greedy Best-First Search <b>ignores path cost (g)</b> entirely
          — it only picks the node with the <b>lowest heuristic h</b> at each step.`
  });

  let guard = 0;
  let goalReached = false;

  while (openSet.size > 0 && guard++ < 300) {
    // Pick node with lowest h
    let current = null, minH = Infinity;
    openSet.forEach(id => { if (openMap[id] < minH) { minH = openMap[id]; current = id; } });
    if (!current) break;

    if (current === 'G') {
      // Reconstruct path
      let n = 'G';
      pathNodes = new Set();
      while (n) { pathNodes.add(n); n = parent[n]; }
      let n2 = 'G';
      while (parent[n2]) {
        pathEdges.add([n2, parent[n2]].sort().join('|'));
        n2 = parent[n2];
      }
      goalReached = true;
      steps.push({
        type: 'goal', current, neighbors: [], activeEdge: null,
        open: { ...openMap }, closed: new Set(closedSet),
        path: new Set(pathNodes), pathEdges: new Set(pathEdges),
        msg: `&#127937; <b style="color:#ff88aa">Goal reached!</b>
              Node <b style="color:#ffee00">G</b> is dequeued — it has h = <b>0</b>, the lowest possible.
              Greedy found <i>a</i> path, but it may <b style="color:#ff6644">not be the shortest one!</b>
              Compare with A* to see the true optimal route.`
      });
      break;
    }

    // Remove from open, add to closed
    const pickedH = openMap[current];
    openSet.delete(current);
    delete openMap[current];
    closedSet.add(current);

    // Build competing candidates string for educational context
    const competingEntries = Object.entries(openMap).sort((a, b) => a[1] - b[1]);
    const competingStr = competingEntries.length > 0
      ? competingEntries.map(([id, h]) => `h(${id})=${h}`).join(', ')
      : 'none';

    steps.push({
      type: 'pick', current, neighbors: [], activeEdge: null,
      open: { ...openMap }, closed: new Set(closedSet),
      path: new Set(pathNodes), pathEdges: new Set(pathEdges),
      msg: `&#128205; <b style="color:#ff88aa">Greedy picks lowest-h node.</b>
            &nbsp; Node <b style="color:#ff1166">${current}</b> has h = <b>${pickedH}</b>
            ${competingEntries.length > 0
              ? `(better than remaining: ${competingStr})`
              : '(only node in Open List)'}.
            Greedy <b>does not consider how far it traveled to get here</b> — only where it thinks the goal is.
            Moving ${current} to <b style="color:#aa3333">Closed List</b>.`
    });

    // Expand neighbors
    const nbrs = adjacency[current];
    nbrs.forEach(({ to, w }) => {
      if (closedSet.has(to)) {
        // Educational: show skipped closed node
        const eKey = [current, to].sort().join('|');
        steps.push({
          type: 'skip_closed', current, neighbors: [to], activeEdge: eKey,
          open: { ...openMap }, closed: new Set(closedSet),
          path: new Set(pathNodes), pathEdges: new Set(pathEdges),
          msg: `&#128683; <b style="color:#ff88aa">Skipping neighbor</b>
                <b style="color:#cc4455">${to}</b> (h=${heuristic[to]}).
                It is already in the <b style="color:#aa3333">Closed List</b> — already evaluated.
                Greedy never revisits closed nodes.`
        });
        return;
      }

      const h   = heuristic[to];
      const eKey = [current, to].sort().join('|');
      const isNew = !openSet.has(to);

      if (isNew) {
        openSet.add(to);
        openMap[to] = h;
        parent[to]  = current;
        steps.push({
          type: 'discover', current, neighbors: [to], activeEdge: eKey,
          open: { ...openMap }, closed: new Set(closedSet),
          path: new Set(pathNodes), pathEdges: new Set(pathEdges),
          msg: `&#128270; <b style="color:#ff88aa">Discovered neighbor</b>
                <b style="color:#cc88ff">${to}</b> via ${current}.
                h(${to}) = <b>${h}</b>.
                Added to <b style="color:#9922cc">Open List</b>.
                ${to === 'T'
                  ? `&#9888;&#65039; <b style="color:#ff6633">T looks promising (h=${h})!</b> Greedy will be lured here — but T is a dead end with no path to G!`
                  : `Greedy only records h(${to}) = ${h}; path cost is ignored.`}`
        });
      } else {
        // Already in open — Greedy doesn't update (no g cost to compare)
        steps.push({
          type: 'already_open', current, neighbors: [to], activeEdge: eKey,
          open: { ...openMap }, closed: new Set(closedSet),
          path: new Set(pathNodes), pathEdges: new Set(pathEdges),
          msg: `&#128260; <b style="color:#ff88aa">Neighbor ${to} already in Open List</b>
                (h=${h}). Greedy does <b>not update</b> it — without tracking g costs,
                there is no notion of a "better" route to ${to}. It stays as-is.`
        });
      }
    });

    // Special: if current was T (dead end) — teach about the trap
    if (current === 'T') {
      steps.push({
        type: 'deadend', current: 'T', neighbors: [], activeEdge: null,
        open: { ...openMap }, closed: new Set(closedSet),
        path: new Set(pathNodes), pathEdges: new Set(pathEdges),
        msg: `&#128165; <b style="color:#ff4422">Dead end!</b>
              Node <b style="color:#ff1166">T</b> has h=${heuristic['T']} — the best heuristic value seen so far.
              Greedy rushed here because h looked great, <b>completely ignoring the actual path cost</b>.
              But T only connects back to C, which is already closed.
              This is the core weakness of Greedy: <b style="color:#ffaa44">a low h does not guarantee a good path.</b>
              Backtracking to find another route...`
      });
    }
  }

  if (!goalReached) {
    steps.push({
      type: 'no_path', current: null, neighbors: [], activeEdge: null,
      open: {}, closed: new Set(closedSet),
      path: new Set(), pathEdges: new Set(),
      msg: `&#9888;&#65039; <b style="color:#ff4444">No path found.</b>
            Open List exhausted. Goal G is unreachable from S with this graph.`
    });
  }

  return steps;
}

// ─── Apply Step to Scene ──────────────────────────────────────────────────────
function applyStep(step) {
  NODE_DEFS.forEach(n => {
    let col;
    if (step.path.has(n.id))               col = n.id === 'G' ? C.GOAL : (n.id === 'S' ? C.START : C.PATH);
    else if (n.id === step.current)        col = C.CURRENT;
    else if (step.neighbors.includes(n.id)) col = C.OPEN;
    else if (step.closed.has(n.id))        col = C.CLOSED;
    else if (step.open[n.id] !== undefined) col = C.OPEN;
    else if (n.id === 'S')                 col = C.START;
    else if (n.id === 'G')                 col = C.GOAL;
    else                                   col = C.UNVISITED;

    const mesh = nodeMeshes[n.id];
    const glow = nodeGlows[n.id];
    const ring = nodeRings[n.id];

    mesh.material.color.setHex(col);
    mesh.material.emissive.setHex(col === C.UNVISITED ? 0x060204 : col);
    mesh.material.emissiveIntensity = col === C.UNVISITED ? 0.04 : 0.26;

    glow.material.color.setHex(col);
    glow.material.opacity = col === C.UNVISITED ? 0.04 : 0.22;

    const isActive = (n.id === step.current || step.neighbors.includes(n.id));
    ring.material.color.setHex(col);
    ring.material.opacity = isActive ? 0.65 : (step.open[n.id] !== undefined ? 0.28 : 0.0);
  });

  edgeMeshes.forEach(e => {
    const eKey = [e.from, e.to].sort().join('|');
    let col = C.EDGE_DEF, opa = 0.35;
    if (step.pathEdges.has(eKey))                      { col = C.EDGE_PATH; opa = 1.0; }
    else if (step.activeEdge === eKey)                 { col = C.EDGE_ACT;  opa = 1.0; }
    else if (step.open[e.from] !== undefined ||
             step.open[e.to]   !== undefined)          { col = C.EDGE_OPEN; opa = 0.50; }
    e.mat.color.setHex(col);
    e.mat.opacity = opa;
  });

  infoPanel.innerHTML =
    `<span style="color:#3a1020;font-size:11px;letter-spacing:1px">GREEDY BEST-FIRST SEARCH</span>
     &nbsp;&nbsp;<span style="color:#2a0a14;font-size:11px">Step ${stepIndex + 1} / ${steps.length}</span>
     <br/><span style="font-size:13px">${step.msg}</span>`;

  // Side panel: Open List sorted by h
  const openEntries = Object.entries(step.open).sort((a, b) => a[1] - b[1]);
  let openRows = '';
  openEntries.forEach(([id, h]) => {
    const isBest = openEntries.length > 0 && h === openEntries[0][1];
    openRows += `<div style="display:flex;justify-content:space-between;gap:10px;
      line-height:1.9;border-bottom:1px solid rgba(80,10,30,0.4);padding:1px 0">
      <span style="color:#cc55ff;font-weight:bold">${id}</span>
      <span style="color:#5a1a44">h = <b style="color:${isBest ? '#ff88cc' : '#996688'}">${h}</b></span>
      ${isBest ? '<span style="color:#ff1166;font-size:10px">&#9650; next</span>' : ''}
    </div>`;
  });

  let closedRows = '';
  step.closed.forEach(id => {
    closedRows += `<div style="display:flex;justify-content:space-between;gap:10px;
      line-height:1.9;border-bottom:1px solid rgba(50,5,15,0.4);padding:1px 0">
      <span style="color:#7a2233;font-weight:bold">${id}</span>
      <span style="color:#3a0a18">h = <b style="color:#663344">${heuristic[id]}</b></span>
    </div>`;
  });

  sidePanel.innerHTML =
    `<div style="color:#3a1020;font-size:11px;letter-spacing:1px;margin-bottom:8px">PRIORITY QUEUE</div>
     <div style="color:#3a0a30;font-size:11px;margin-bottom:6px;letter-spacing:0.5px">
       &#9654; OPEN&nbsp;<span style="float:right;color:#220a18">${openEntries.length} nodes</span></div>
     <div style="color:#2a0a1a;font-size:10px;margin-bottom:6px;font-style:italic">sorted by h (low = first)</div>
     ${openRows || '<div style="color:#2a0a18;font-size:11px">Empty</div>'}
     <div style="color:#440a1a;font-size:11px;margin:12px 0 4px;letter-spacing:0.5px">
       &#9654; CLOSED&nbsp;<span style="float:right;color:#1a0508">${step.closed.size} nodes</span></div>
     ${closedRows || '<div style="color:#1a0508;font-size:11px">Empty</div>'}`;

  const pct = steps.length > 1 ? (stepIndex / (steps.length - 1)) * 100 : 0;
  progressBar.style.width = pct + '%';
  progressLabel.textContent = `Step ${stepIndex + 1} / ${steps.length}`;
}

// ─── State Machine ────────────────────────────────────────────────────────────
let steps     = [];
let stepIndex = 0;
let isPlaying = false;
let playTimer = null;

function initAlgo() {
  steps     = generateSteps();
  stepIndex = 0;
  applyStep(steps[0]);
}

function doNext() {
  if (stepIndex < steps.length - 1) { stepIndex++; applyStep(steps[stepIndex]); }
  else stopPlay();
}

function stopPlay() {
  isPlaying = false;
  if (playTimer) { clearTimeout(playTimer); playTimer = null; }
  autoBtn.innerHTML = '&#9654;&#9654; Auto Play';
}

function startPlay() {
  isPlaying = true;
  autoBtn.innerHTML = '&#9646;&#9646; Pause';
  function tick() {
    if (!isPlaying) return;
    if (stepIndex < steps.length - 1) {
      doNext();
      const delay = Math.round(1600 - parseInt(speedSlider.value) * 140);
      playTimer = setTimeout(tick, delay);
    } else stopPlay();
  }
  playTimer = setTimeout(tick, Math.round(1600 - parseInt(speedSlider.value) * 140));
}

nextBtn.addEventListener('click',    () => { stopPlay(); doNext();   });
restartBtn.addEventListener('click', () => { stopPlay(); initAlgo(); });
autoBtn.addEventListener('click',    () => { isPlaying ? stopPlay() : startPlay(); });

// ─── Raycaster / Hover ────────────────────────────────────────────────────────
const raycaster = new THREE.Raycaster();
const mouse     = new THREE.Vector2(-9999, -9999);

window.addEventListener('mousemove', e => {
  mouse.x =  (e.clientX / window.innerWidth)  * 2 - 1;
  mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
  tooltip.style.left = (e.clientX + 16) + 'px';
  tooltip.style.top  = (e.clientY - 14) + 'px';
});

function project(pos3d) {
  const v = pos3d.clone().project(camera);
  return {
    x: ( v.x * 0.5 + 0.5) * window.innerWidth,
    y: (-v.y * 0.5 + 0.5) * window.innerHeight,
    behind: v.z > 1.0
  };
}

// ─── Animation Loop ───────────────────────────────────────────────────────────
const clock = new THREE.Clock();

function animate() {
  requestAnimationFrame(animate);
  const t = clock.getElapsedTime();
  controls.update();

  NODE_DEFS.forEach((n, i) => {
    const mesh = nodeMeshes[n.id];
    const glow = nodeGlows[n.id];
    const ring = nodeRings[n.id];
    ring.lookAt(camera.position);

    const col      = mesh.material.color.getHex();
    const isActive = (col === C.CURRENT || col === C.OPEN);
    const floatY   = n.pos.y + Math.sin(t * 0.72 + i * 1.18) * 0.05;

    if (isActive) {
      const pulse = 1 + 0.10 * Math.sin(t * 5.8);
      mesh.scale.setScalar(pulse);
      glow.scale.setScalar(pulse * 1.12);
      ring.scale.setScalar(1 + 0.15 * Math.sin(t * 4.0 + 0.3));
    } else {
      mesh.scale.setScalar(col === C.PATH ? 1.10 : 1.0);
      glow.scale.setScalar(1.0);
      ring.scale.setScalar(1.0);
    }

    mesh.position.y = floatY;
    glow.position.y = floatY;
    ring.position.y = floatY;
  });

  keyLight.position.x  =  5 + Math.sin(t * 0.26) * 2.2;
  keyLight.position.z  =  8 + Math.cos(t * 0.21) * 2.0;
  fillLight.position.x = -10 + Math.cos(t * 0.19) * 1.6;

  // Raycasting
  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObjects(NODE_DEFS.map(n => nodeMeshes[n.id]));
  if (hits.length > 0) {
    const id  = hits[0].object.userData.id;
    const h   = heuristic[id];
    const step = steps[stepIndex] || {};
    const inOpen   = step.open   && step.open[id]   !== undefined;
    const inClosed = step.closed && step.closed.has(id);
    const status   = inOpen ? '<span style="color:#cc55ff">In Open List</span>'
                   : inClosed ? '<span style="color:#882233">In Closed List</span>'
                   : id === step.current ? '<span style="color:#ff1166">Currently evaluating</span>'
                   : '<span style="color:#442030">Unvisited</span>';
    tooltip.style.display = 'block';
    tooltip.innerHTML =
      `<b style="color:#ff88aa;font-size:13px">Node ${id}</b><br>
       h (heuristic to G): <b style="color:#ffbb44">${h}</b><br>
       ${id === 'T' ? '<span style="color:#ff6633">&#9888; Dead end — no edge to G!</span><br>' : ''}
       Status: ${status}`;
  } else {
    tooltip.style.display = 'none';
  }

  // Project node labels
  NODE_DEFS.forEach(n => {
    const p    = project(nodeMeshes[n.id].position);
    const lbl  = nodeLabels[n.id];
    const hlbl = hLabels[n.id];
    if (p.behind) { lbl.style.display = 'none'; hlbl.style.display = 'none'; return; }
    lbl.style.display  = 'block';
    lbl.style.left     = p.x + 'px';
    lbl.style.top      = (p.y - 28) + 'px';
    hlbl.style.display = 'block';
    hlbl.style.left    = p.x + 'px';
    hlbl.style.top     = (p.y + 22) + 'px';
  });

  // Project edge weight labels
  weightLabels.forEach(w => {
    const p = project(w.mid);
    if (p.behind) { w.d.style.display = 'none'; return; }
    w.d.style.display = 'block';
    w.d.style.left    = p.x + 'px';
    w.d.style.top     = p.y + 'px';
  });

  renderer.render(scene, camera);
}

window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

initAlgo();
animate();
"""

def get_greedy_content():
    return {
        "title": "Greedy Algorithms",
        "text_explanation": text_content,
        "media_type": "python_code",
        "code": canvas_payload
    }
